version: "3.9"
services:
  build:
    image: exercise-2
    build:
      context: ../../
      dockerfile: ./Exercises/Exercise-2/Dockerfile
  tests:
    depends_on:
      - build
    image: exercise-2
    command: pipenv run python -m pytest
  run:
    depends_on:
      - build
    image: exercise-2
    command: pipenv run python main.py regex
