---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: (.*\.csv)|(.*\.json)
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        args: [--in-place, --remove-all-unused-imports, --remove-unused-variable]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, pep8-naming]

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
      - id: bandit
        args: [--skip, "B101"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.982'
    hooks:
      - id: mypy
        args: [--no-strict-optional,  --ignore-missing-imports]
        additional_dependencies: [types-requests, pandas-stubs, pytest-stub]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint-docker
        args: [--ignore, "DL3008", --ignore, "DL4006"]
