version: "3.9"
services:
  postgresdb:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=exercise_user
      - POSTGRES_DB=exercise_database
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U exercise_user -d exercise_database"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  build-and-run:
    image: exercise-5
    depends_on:
      postgresdb:
        condition: service_healthy
    build:
      context: ../../
      dockerfile: ./Exercises/Exercise-5/Dockerfile
    command: pipenv run python main.py
