version: "3.9"
services:
  build:
    image: exercise-6
    build:
      context: ../../
      dockerfile: ./Exercises/Exercise-6/Dockerfile
  tests:
    depends_on:
      - build
    image: exercise-6
    command: pipenv run python -m pytest
  run:
    depends_on:
      - build
    image: exercise-6
    command: pipenv run python main.py
