version: "3.9"
services:
  build-and-run:
    image: exercise-3
    build:
      context: ../../
      dockerfile: ./Exercises/Exercise-3/Dockerfile
    volumes:
      - $HOME/.aws:/root/.aws:ro
    command: pipenv run python main.py
